spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: {OAUTH2_CLIENT_ID}
            client-secret: {OAUTH2_CLIENT_SECRET}
            redirect-uri: {OAUTH2_KAKAO_REDIRECT_URI}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id